# Generated by Django 3.1.6 on 2021-10-31 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=25)),
                ('lastName', models.CharField(max_length=25)),
                ('emailId', models.EmailField(max_length=25)),
                ('mobileNo', models.IntegerField(blank=True)),
                ('city', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=250)),
            ],
        ),
    ]
