# Generated by Django 3.1.6 on 2021-10-31 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='city',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='emailId',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='firstName',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='lastName',
            field=models.CharField(max_length=30),
        ),
    ]
